### ISSUE TITLE
move todo to issues

### ISSUE THREAD

**Issue by butlerx** [redbrick/useradm#11]
https://github.com/redbrick/useradm/blob/master/TODO

**Comment by RodolfoFerro** [comment]
I've already done this, as you can see in https://github.com/redbrick/useradm/pull/58 .
I've seen that many of them had (kind of) updates saying 'DONE' in the TODO file.

Would you mind to close those issues @butlerx ?
I didn't want to because some of them were written like 'DONE?' and I wasn't really sure that those were indeed done.

**Comment by butlerx** [comment]
Thanks I'll review those issues to see if they are done/still relevant
